### ISSUE TITLE
icon size

### ISSUE THREAD

**Issue by highthamok** [corygibbons/react-file-icon#19]
How can change the size of the icon ? 
thank you

**Comment by abhishek-v-sfs** [comment]
@highthamok  You can try wrapping the component in a div and try applying styles to that div.      
```
<div style={{ width: "5%" }}>
        <FileIcon extension="docx" {...defaultStyles.docx} />
</div>
```
Hope this helps.

**Comment by abhi0498** [comment]
@highthamok You can try wrapping the component in a div and try applying styles to that div.

```
<div style={{ width: "5%" }}>
        <FileIcon extension="docx" {...defaultStyles.docx} />
</div>
```
Hope this helps.

**Comment by corygibbons** [comment]
The icon will scale up to fit its parent so @abhi0498 is right that setting a width on a wrapper is the way to go.
