### ISSUE TITLE
Doesn't install on React 18 due to a dependency issue

### ISSUE THREAD

**Issue by indicava** [corygibbons/react-file-icon#34]
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^17.0.0 || ^16.2.0" from react-file-icon@1.1.0
npm ERR! node_modules/react-file-icon
npm ERR!   react-file-icon@"*" from the root project

Any chance to fix the dependency tree to suport React 18?

**Comment by corygibbons** [comment]
Yeah I'll look into this 👍
