### ISSUE TITLE
Bundle Size

### ISSUE THREAD

**Issue by lounsbrough** [corygibbons/react-file-icon#37]
Hi there! I noticed that when I pull this package into our project, the `tinycolor2` dependency is a little large (14KB parsed from webpack):

![image](https://user-images.githubusercontent.com/8313853/207390317-74563160-aac5-439e-8d91-b72cc8d0306e.png)

It looks like the only reason this package is used is to darken a user-provided color in 3 places. Is there a lighter package that could accomplish this, or could we pull that logic into this code base? Would you be open to a PR if I were to put one up?

Thanks!

**Comment by corygibbons** [comment]
@lounsbrough This has been bugging me as well but haven't had a chance to look into it much yet.

There are some really lightweight ways to darken colors but they usually require a specific input, however we're relying on `tinycolor2` to handle our ambiguous `color` prop (named, hex, rgb, etc.) So we'd either need another way to convert that or force a type like hex (less ideal currently)

[`colord`](https://github.com/omgovich/colord) (6kb) looks like it could be good for a pretty low effort swap, and it's less than half the size. 🤷‍♂️

Open to a PR if you have any ideas.

**Comment by lounsbrough** [comment]
Cool, yeah `colord` does look better to me. If you're good with that, here's the PR: https://github.com/corygibbons/react-file-icon/pull/38/files

**Comment by corygibbons** [comment]
b930de0588e999f6f507189b2c97097539cf6982
